/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testdb;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static testdb.Ventana.Mostrar2;

/**
 *
 * @author neiseil
 */
public class ModificarProducto extends javax.swing.JDialog {

    Conectar con = new Conectar();
    Connection cn = con.conexion();
    String atributo="ID_PRODUCTO";
    /**
     * Creates new form ModificarProducto
     */
    public ModificarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        agregarItem();
        
    }
void mostrartabla(String valor)
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("TIPO");
        modelo.addColumn("CONTENIDO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRECIO VENTA");
        modelo.addColumn("PROVEEDOR");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("PRECIO COMPRA");
        Ventana.Mostrar2.setModel(modelo);
        
        String sql = "";
        if(valor.equals(""))
        {
            sql = "SELECT PRODUCTO.ID_PRODUCTO,NOMBRE_PROD,ID_T,CANTIDAD,DESCRIPCION_P,PRECIO,NOMBRE_PR,TELEFONO,PRECIO_COMPRA FROM PRODUCTO INNER JOIN OFRECEN ON PRODUCTO.ID_PRODUCTO=OFRECEN.ID_PRODUCTO INNER JOIN PROVEEDOR ON OFRECEN.ID_PROVEEDOR=PROVEEDOR.ID_PROVEEDOR ORDER BY PROVEEDOR.ID_PROVEEDOR";
        }
        else
        {
            sql = "SELECT PRODUCTO.ID_PRODUCTO,NOMBRE_PROD,ID_T,CANTIDAD,DESCRIPCION_P,PRECIO,NOMBRE_PR,TELEFONO,PRECIO_COMPRA FROM PRODUCTO INNER JOIN OFRECEN ON PRODUCTO.ID_PRODUCTO=OFRECEN.ID_PRODUCTO INNER JOIN PROVEEDOR ON OFRECEN.ID_PROVEEDOR=PROVEEDOR.ID_PROVEEDOR WHERE "+atributo+"='"+valor+"' ORDER BY PROVEEDOR.ID_PROVEEDOR";
        }
        String datos[] = new String [9];
        Statement st;
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);

                modelo.addRow(datos);
            }
            Ventana.Mostrar2.setModel(modelo);
        } catch (SQLException ex)
        {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    void limpiar_campos()
    {
        CAMP1.setText("");
        CAMP2.setText("");
        Select_tipo.setSelectedIndex(0);
        CAMP4.setText("");
        CAMP5.setText("");
        CAMP6.setText("");
        Select_proveedor.setSelectedItem("Seleccionar");
        CAMP7.setText("");
    }
    
    void agregarItem()
    {
        Select_tipo.addItem("FRUTAS");
        Select_tipo.addItem("BEBIDAS");
        Select_tipo.addItem("VERDURAS");
        Select_tipo.addItem("ABARROTES");
        Select_proveedor.addItem("PROVEEDOR1");
        Select_proveedor.addItem("PROVEEDOR2");
        Select_proveedor.addItem("PROVEEDOR3");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mod_Prod = new javax.swing.JPanel();
        CAMP2 = new javax.swing.JTextField();
        CAMP4 = new javax.swing.JTextField();
        CAMP5 = new javax.swing.JTextField();
        CAMP6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Select_tipo = new javax.swing.JComboBox<>();
        CAMP1 = new javax.swing.JTextField();
        ACTUALIZARMODIFICACION = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Select_proveedor = new javax.swing.JComboBox<>();
        CAMP7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Mod_Prod.setBackground(new java.awt.Color(51, 51, 51));
        Mod_Prod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        Mod_Prod.setForeground(new java.awt.Color(255, 255, 255));

        CAMP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMP6ActionPerformed(evt);
            }
        });
        CAMP6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CAMP6KeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Capacidad");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Precio Venta");

        Select_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        Select_tipo.setToolTipText("");

        CAMP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMP1ActionPerformed(evt);
            }
        });
        CAMP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CAMP1KeyTyped(evt);
            }
        });

        ACTUALIZARMODIFICACION.setText("Guardar");
        ACTUALIZARMODIFICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZARMODIFICACIONActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Proveedor");

        Select_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        CAMP7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CAMP7KeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precio Compra");

        javax.swing.GroupLayout Mod_ProdLayout = new javax.swing.GroupLayout(Mod_Prod);
        Mod_Prod.setLayout(Mod_ProdLayout);
        Mod_ProdLayout.setHorizontalGroup(
            Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mod_ProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mod_ProdLayout.createSequentialGroup()
                        .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Select_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CAMP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(CAMP2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CAMP4, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(Mod_ProdLayout.createSequentialGroup()
                        .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CAMP5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Mod_ProdLayout.createSequentialGroup()
                                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Select_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CAMP7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CAMP6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ACTUALIZARMODIFICACION)))
                        .addGap(18, 18, 18))))
        );
        Mod_ProdLayout.setVerticalGroup(
            Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mod_ProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CAMP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CAMP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Select_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CAMP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(CAMP5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CAMP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mod_ProdLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ACTUALIZARMODIFICACION))
                    .addGroup(Mod_ProdLayout.createSequentialGroup()
                        .addComponent(Select_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Mod_ProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CAMP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mod_Prod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mod_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CAMP6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CAMP6KeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_CAMP6KeyTyped

    private void CAMP1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CAMP1KeyTyped

        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();

    }//GEN-LAST:event_CAMP1KeyTyped

    private void CAMP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMP1ActionPerformed

    private void ACTUALIZARMODIFICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZARMODIFICACIONActionPerformed
        if (CAMP1.getText()=="" || CAMP2.getText()=="" || Select_tipo.getSelectedIndex()==0 || CAMP4.getText()=="" || CAMP5.getText()=="" || CAMP6.getText()==""){
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacíos");}
        else{
            try {
                int fila = Ventana.Mostrar2.getSelectedRow();

                if (fila>=0){ 
                    PreparedStatement pps = cn.prepareStatement("UPDATE PRODUCTO SET ID_PRODUCTO='"+CAMP1.getText()+"',NOMBRE_PROD='"+CAMP2.getText()+"',ID_T='"+Select_tipo.getSelectedItem().toString()+"',CANTIDAD='"+CAMP4.getText()+"',DESCRIPCION_P='"+CAMP5.getText()+"',PRECIO='"+CAMP6.getText()+"' WHERE ID_PRODUCTO='"+Ventana.Mostrar2.getValueAt(fila, 0).toString()+"'");
                    pps.executeUpdate();
                    if (Select_proveedor.getSelectedIndex()==0)
                    {
                        pps = cn.prepareStatement("UPDATE OFRECEN SET ID_PRODUCTO='"+CAMP1.getText()+"',ID_PROVEEDOR='"+4+"',PRECIO_COMPRA='"+CAMP7.getText()+"' WHERE ID_PRODUCTO='"+Ventana.Mostrar2.getValueAt(fila, 0).toString()+"'");
                    }
                    else{
                    pps = cn.prepareStatement("UPDATE OFRECEN SET ID_PRODUCTO='"+CAMP1.getText()+"',ID_PROVEEDOR='"+Select_proveedor.getSelectedIndex()+"',PRECIO_COMPRA='"+CAMP7.getText()+"' WHERE ID_PRODUCTO='"+Ventana.Mostrar2.getValueAt(fila, 0).toString()+"'");
                    }
                    pps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Datos modificados ");
                    mostrartabla("");
                    this.setVisible(false);

                }

            } catch (SQLException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_ACTUALIZARMODIFICACIONActionPerformed

    private void CAMP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMP6ActionPerformed

    private void CAMP7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CAMP7KeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_CAMP7KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarProducto dialog = new ModificarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZARMODIFICACION;
    public static javax.swing.JTextField CAMP1;
    public static javax.swing.JTextField CAMP2;
    public static javax.swing.JTextField CAMP4;
    public static javax.swing.JTextField CAMP5;
    public static javax.swing.JTextField CAMP6;
    public static javax.swing.JTextField CAMP7;
    private javax.swing.JPanel Mod_Prod;
    public static javax.swing.JComboBox<String> Select_proveedor;
    public static javax.swing.JComboBox<String> Select_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
